# THIS FILE IS EXCLUSIVELY MAINTAINED by the project aedev.project_tpls v0.3.105
""" setup of aedev namespace package portion project_manager: maintain Python projects locally and remotely. """
import pathlib
import sys
from typing import Any
import setuptools


print("SetUp " + __name__ + ": " + sys.executable + str(sys.argv) + f" {sys.path=}")

setup_kwargs: dict[str, Any] = {
    'author': 'AndiEcker',
    'author_email': 'aecker2@gmail.com',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.12',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Typing :: Typed',
    ],
    'description': 'aedev namespace package portion project_manager: maintain Python projects locally and remotely',
    'entry_points': {
        'console_scripts': [
            'pjm = aedev.project_manager.__main__:main',
            'project-manager = aedev.project_manager.__main__:main',
        ],
    },
    'extras_require': {
        'dev': [
            'aedev_project_tpls==0.3.105',
            'aedev_aedev==0.3.35',
            'ae_app_log==0.3.4',
            'ae_base==0.3.97',
            'ae_console==0.3.98',
            'ae_core==0.3.89',
            'ae_dynamicod==0.3.16',
            'ae_files==0.3.31',
            'ae_literal==0.3.36',
            'ae_managed_files==0.3.9',
            'ae_paths==0.3.47',
            'ae_pythonanywhere==0.3.10',
            'ae_shell==0.3.19',
            'ae_sys_core==0.3.27',
            'ae_system==0.3.20',
            'ae_updater==0.3.20',
            'aedev_app_tpls==0.3.22',
            'aedev_base==0.3.12',
            'aedev_commands==0.3.20',
            'aedev_namespace_root_tpls==0.3.33',
            'aedev_project_vars==0.3.25',
            'alabaster==1.0.0',
            'anybadge==1.16.0',
            'argcomplete==3.6.3',
            'ast_serialize==0.6.0',
            'astroid==4.0.4',
            'babel==2.18.0',
            'certifi==2026.6.17',
            'cffi==2.0.0',
            'charset-normalizer==3.4.7',
            'click==8.4.1',
            'coverage==7.16.1',
            'cryptography==49.0.0',
            'dill==0.4.1',
            'docutils==0.22.4',
            'filelock==3.30.0',
            'flake8==7.4.1',
            'idna==3.18',
            'imagesize==2.0.0',
            'iniconfig==2.3.0',
            'isort==8.0.1',
            'Jinja2==3.1.6',
            'librt==0.13.0',
            'MarkupSafe==3.0.3',
            'mccabe==0.7.0',
            'mypy==2.3.1',
            'mypy_extensions==1.1.0',
            'packaging==26.3',
            'pathspec==1.1.1',
            'pillow==12.3.0',
            'pipx==1.17.6',
            'platformdirs==4.10.0',
            'pluggy==1.6.0',
            'psycopg2-binary==2.9.13',
            'pyasn1==0.6.4',
            'pyasn1_modules==0.4.2',
            'pycodestyle==2.15.0',
            'pycparser==3.0',
            'pyflakes==4.0.1',
            'PyGithub==2.10.0',
            'Pygments==2.20.0',
            'pyjnius==1.7.0',
            'PyJWT==2.13.0',
            'pylint==4.0.9',
            'PyNaCl==1.6.2',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'python-gitlab==8.6.0',
            'requests==2.34.2',
            'requests-toolbelt==1.0.0',
            'roman-numerals==4.1.0',
            'setuptools==84.0.0',
            'snowballstemmer==3.1.1',
            'Sphinx==9.1.0',
            'sphinx-autodoc-typehints==3.13.8',
            'sphinx-paramlinks==0.6.0',
            'sphinx_rtd_theme==3.1.0',
            'sphinxcontrib-applehelp==2.0.0',
            'sphinxcontrib-devhelp==2.0.0',
            'sphinxcontrib-htmlhelp==2.1.0',
            'sphinxcontrib-jquery==4.1',
            'sphinxcontrib-jsmath==1.0.1',
            'sphinxcontrib-qthelp==2.0.0',
            'sphinxcontrib-serializinghtml==2.0.0',
            'tomlkit==0.15.0',
            'types-Pillow==10.2.0.20240822',
            'types-requests==2.33.0.20260906',
            'types-setuptools==84.0.0.20260812',
            'typing==3.7.4.3',
            'typing_extensions==4.16.0',
            'urllib3==2.7.0',
            'userpath==1.9.2',
            'anybadge==1.16.0',
            'flake8==7.4.1',
            'mypy==2.3.1',
            'pylint==4.0.9',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'typing==3.7.4.3',
            'types-setuptools==84.0.0.20260812',
        ],
        'docs': [],
        'tests': [
            'anybadge==1.16.0',
            'flake8==7.4.1',
            'mypy==2.3.1',
            'pylint==4.0.9',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'typing==3.7.4.3',
            'types-setuptools==84.0.0.20260812',
        ],
    },
    'install_requires': [
        'anybadge==1.16.0',
        'coverage==7.16.1',
        'flake8==7.4.1',
        'mypy==2.3.1',
        'packaging==26.3',
        'pillow==12.3.0',
        'types-Pillow==10.2.0.20240822',
        'PyGithub==2.10.0',
        'pylint==4.0.9',
        'pytest==9.1.1',
        'pytest-cov==7.1.0',
        'python-gitlab==8.6.0',
        'requests==2.34.2',
        'ae_base==0.3.97',
        'ae_system==0.3.20',
        'ae_paths==0.3.47',
        'ae_dynamicod==0.3.16',
        'ae_literal==0.3.36',
        'ae_updater==0.3.20',
        'ae_core==0.3.89',
        'ae_console==0.3.98',
        'ae_shell==0.3.19',
        'ae_managed_files==0.3.9',
        'ae_pythonanywhere==0.3.10',
        'aedev_base==0.3.12',
        'aedev_commands==0.3.20',
        'aedev_project_vars==0.3.25',
    ],
    'keywords': [
        'configuration',
        'development',
        'environment',
        'productivity',
    ],
    'license': 'GPL-3.0-or-later',
    'long_description': (pathlib.Path(__file__).parent / 'README.md').read_text(encoding='utf-8'),
    'long_description_content_type': 'text/markdown',
    'name': 'aedev_project_manager',
    'package_data': {
        '': [],
    },
    'packages': [
        'aedev.project_manager',
    ],
    'project_urls': {
        'Bug Tracker': 'https://gitlab.com/aedev-group/aedev_project_manager/-/issues',
        'Documentation': 'https://aedev.readthedocs.io/en/latest/_autosummary/aedev.project_manager.html',
        'Repository': 'https://gitlab.com/aedev-group/aedev_project_manager',
        'Source': 'https://aedev.readthedocs.io/en/latest/_modules/aedev/project_manager.html',
    },
    'python_requires': '>=3.12',
    'url': 'https://gitlab.com/aedev-group/aedev_project_manager',
    'version': '0.3.43',
    'zip_safe': True,
}

if __name__ == "__main__":
    setuptools.setup(**setup_kwargs)
    ...
